FROM quay.io/pypa/manylinux2014_x86_64

# Fix the hash in the URL and update this.
ENV AEC_VERSION 1.0.6
ENV HDF5_VERSION 1.14.2
ENV NETCDF_VERSION 4.9.3-dev
ENV OPENSSL_VERSION 3.3.1
ENV CURL_VERSION 8.8.0

ENV BUILD_PREFIX /usr/local

COPY install_libs.sh /tmp/install_libs.sh
RUN bash /tmp/install_libs.sh
