FROM quay.io/pypa/manylinux_2_28_aarch64

# Fix the hash in the URL and update this.
ENV AEC_VERSION=1.1.3
ENV HDF5_VERSION=1.14.6
ENV NETCDF_VERSION=4.9.3
ENV OPENSSL_VERSION=3.5.1
ENV CURL_VERSION=8.14.1

ENV BUILD_PREFIX=/usr/local

COPY install_libs.sh /tmp/install_libs.sh
RUN bash /tmp/install_libs.sh
