name: Build Image from Dockerfile 
on:
  push:
    branches: [ main ]
  workflow_dispatch: null

jobs:
  build_x86_64_wheels:
    name: Build image for x86_64
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        file: ./Dockerfile_x86_64
        platforms: linux/amd64
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/manylinux2014_x86_64-netcdf

  build_aarch64_wheels:
    name: Build image for aarch64
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        file: ./Dockerfile_aarch64
        platforms: linux/arm64
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/manylinux2014_aarch64-netcdf
